source 'https://rubygems.org'
ruby   '2.6.3'

gem 'lita',            '~> 4.8'
gem 'lita-jenkins',    '~> 0.1', git: 'https://github.com/onetwotrip/lita-jenkins.git'
gem 'lita-jira',       git: 'https://github.com/esigler/lita-jira.git'
gem 'lita-jira-issues', git: 'https://github.com/onetwotrip/lita-jira-issues.git'
gem 'lita-log',        '~> 0.4', git: 'https://github.com/onetwotrip/lita-log.git'
gem 'lita-slack',      git: 'https://github.com/onetwotrip/lita-slack.git'
gem 'lita-punk',       git: 'https://github.com/onetwotrip/lita-punk.git'
gem 'lita-trello'
gem 'lita-whois'
gem 'lita_dotenv'
