source 'https://rubygems.org'
ruby   '2.5.1'

gem 'lita',            '~> 4.6'
gem 'lita-jenkins',    '~> 0.1.0', git: 'https://github.com/onetwotrip/lita-jenkins.git'
gem 'lita-jira',       git: 'https://github.com/esigler/lita-jira.git'
gem 'lita-jira-issues'
gem 'lita-log',        '~> 0.4.0', git: 'https://github.com/onetwotrip/lita-log.git'
gem 'lita-slack',      git: 'https://github.com/onetwotrip/lita-slack.git'
gem 'lita-punk',       git: 'https://github.com/onetwotrip/lita-punk.git'
gem 'lita-trello'
gem 'lita-whois'
gem 'lita_dotenv'
